export const NEXT_HERO = 'NEXT_HERO'
export const FIRST_HERO = 'FIRST_HERO'
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

export const LOAD_LINKS_SUCCESS = 'LOAD_LINKS_SUCCESS'


export const SHOW_APP_SUB_MENU = 'SHOW_APP_SUB_MENU'
export const HIDE_APP_SUB_MENU = 'HIDE_APP_SUB_MENU'
